/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#dfb7ff",
        "outline-variant": "#cfc2d4",
        "surface-container": "#efebff",
        "on-secondary-fixed-variant": "#574500",
        "tertiary-fixed": "#ffe083",
        "surface-tint": "#803abd",
        "on-tertiary": "#ffffff",
        "secondary-container": "#fed65b",
        "surface": "#fcf8ff",
        "inverse-on-surface": "#f3eeff",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#574500",
        "on-tertiary-container": "#4e3e00",
        "inverse-surface": "#2d2a5b",
        "on-error": "#ffffff",
        "on-secondary-container": "#745c00",
        "on-secondary-fixed": "#241a00",
        "secondary-fixed": "#ffe088",
        "surface-container-high": "#e9e5ff",
        "primary": "#500088",
        "background": "#fcf8ff",
        "on-primary-fixed-variant": "#661aa3",
        "on-secondary": "#ffffff",
        "surface-dim": "#dad6ff",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#e9c349",
        "surface-variant": "#e3dfff",
        "tertiary-container": "#cea700",
        "on-error-container": "#93000a",
        "inverse-primary": "#dfb7ff",
        "surface-container-lowest": "#ffffff",
        "on-background": "#181445",
        "secondary": "#735c00",
        "on-surface-variant": "#4c4452",
        "tertiary": "#735c00",
        "on-tertiary-fixed": "#231b00",
        "on-primary-container": "#d7a8ff",
        "primary-fixed": "#f1dbff",
        "surface-bright": "#fcf8ff",
        "on-surface": "#181445",
        "primary-container": "#6b21a8",
        "on-primary-fixed": "#2d0050",
        "surface-container-highest": "#e3dfff",
        "surface-container-low": "#f6f2ff",
        "tertiary-fixed-dim": "#eec200",
        "outline": "#7e7383"
      },
      fontFamily: {
        "headline": ["Noto Serif"],
        "body": ["Manrope"],
        "label": ["Manrope"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}
