import About from './About.jsx'
import Contact from './Contact.jsx'
import Home from './Home.jsx'
import Gallery from './Gallery.jsx'
import Header from './Header.jsx'
import Footer from './Footer.jsx'
import Principal from './Principal.jsx'
import Courses from './Courses.jsx'
import Complaints from './Complaints.jsx'
import Admission from './Admission.jsx'
import Faculty from './Faculty.jsx'
import Notice from './Notice.jsx'
import Career from './Career.jsx'
import StudentPortal from './StudentPortal.jsx'
import BelowSocialbtn from './BelowSocialbtn.jsx'
import AdminLoginBtn from './AdminLoginBtn.jsx'
import AdminSignUp from './AdminSignUp.jsx'
import PopupBanner from './PopupBanner.jsx'
import JobApplicationForm from './JobApplicationForm.jsx'

export {About,Contact,Home,Gallery,Header,Footer,Principal,Courses,Complaints,Admission,Faculty,Notice,Career,StudentPortal,BelowSocialbtn,AdminLoginBtn,AdminSignUp,PopupBanner,JobApplicationForm}